modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/SaltFactory/issues"
license="MIT"

[[mods]]
modId="saltfactory"
version="${file.jarVersion}"
displayName="Salt Factory"
logoFile="logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/salt-factory"
authors="Mrbysco"
description='''
Gonna cry? want to turn those tears into salt? Well, you're in the right place.
'''
credits="Darkosto for the idea"
[[dependencies.saltfactory]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"